import { useEffect, useState } from 'react';
import { CheckCircle2, KeyRound } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

type Invitation={email:string;name:string};
export function InvitePage(){const[params]=useSearchParams();const navigate=useNavigate();const token=params.get('token')||'';const[invitation,setInvitation]=useState<Invitation|null>(null);const[error,setError]=useState('');const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[submitting,setSubmitting]=useState(false);const[complete,setComplete]=useState(false);
  useEffect(()=>{if(!token){setError('This invitation link is incomplete.');return}fetch(`/api/auth/invitation?token=${encodeURIComponent(token)}`).then(async(response)=>{const body=await response.json();if(!response.ok)throw new Error(body.error||'Invitation unavailable');setInvitation(body)}).catch((reason)=>setError(reason instanceof Error?reason.message:'Invitation unavailable'))},[token]);
  async function submit(event:React.FormEvent){event.preventDefault();setSubmitting(true);setError('');try{const response=await fetch('/api/auth/invitation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password,passwordConfirm:confirm})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Unable to activate account');setComplete(true);setTimeout(()=>navigate('/'),800)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to activate account')}finally{setSubmitting(false)}}
  return <main className="grid min-h-svh place-items-center bg-background px-5"><div className="w-full max-w-md rounded-xl border bg-card p-7 shadow-sm"><div className="mb-6 grid size-11 place-items-center rounded-full border">{complete?<CheckCircle2 className="size-5 text-emerald-500"/>:<KeyRound className="size-5 text-primary"/>}</div><p className="text-xs uppercase tracking-wider text-muted-foreground">Command Center invitation</p><h1 className="mt-2 text-2xl font-semibold">{complete?'Account ready':invitation?`Welcome, ${invitation.name}`:'Open invitation'}</h1>{invitation&&!complete&&<p className="mt-2 text-sm text-muted-foreground">Create a built-in password for <span className="text-foreground">{invitation.email}</span>.</p>}{complete?<p className="mt-4 text-sm text-muted-foreground">Taking you to your workspace…</p>:invitation?<form className="mt-6 space-y-4" onSubmit={submit}><label className="block space-y-2"><span className="text-xs font-medium">Password</span><Input autoFocus minLength={12} type="password" value={password} onChange={(e)=>setPassword(e.target.value)}/></label><label className="block space-y-2"><span className="text-xs font-medium">Confirm password</span><Input minLength={12} type="password" value={confirm} onChange={(e)=>setConfirm(e.target.value)}/></label>{error&&<p className="text-xs text-destructive">{error}</p>}<Button className="w-full" disabled={password.length<12||password!==confirm||submitting}>{submitting?'Activating…':'Activate account'}</Button></form>:<p className="mt-4 text-sm text-destructive">{error||'Checking invitation…'}</p>}</div></main>}
