import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bot, Copy, KeyRound, MoreHorizontal, Plus, RefreshCw } from 'lucide-react';
import { createServicePrincipal, listServicePrincipals, rotateServicePrincipalCredential, updateServicePrincipalStatus } from '@/api/client';
import { PageHeader } from '@/components/PageHeader';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';

export function ServicePrincipalsPage(){
  const client=useQueryClient(); const principals=useQuery({queryKey:['service-principals'],queryFn:listServicePrincipals}); const [adding,setAdding]=useState(false); const [credential,setCredential]=useState('');
  return <div><PageHeader eyebrow="Command Center" title="Service principals" description="Manage non-human identities used by automation. Mission execution is granted explicitly from Access." actions={<Button size="sm" onClick={()=>setAdding(true)}><Plus/>New principal</Button>}/>
	<div className="overflow-hidden rounded-md border bg-card"><div className="grid grid-cols-[minmax(0,1fr)_8rem_10rem_2rem] gap-3 border-b bg-muted/30 px-4 py-2 text-[10px] uppercase tracking-wider text-muted-foreground"><span>Principal</span><span>Status</span><span>Last used</span><span/></div>
	  {principals.data?.map((principal)=><PrincipalRow key={principal.id} principal={principal} onCredential={setCredential}/>) }
      {principals.isLoading&&<State text="Loading service principals…"/>}{principals.isError&&<State text="Unable to load service principals."/>}{principals.data?.length===0&&<State text="No service principals yet."/>}
    </div><CreateDialog open={adding} onOpenChange={setAdding} onCreated={(value)=>{client.invalidateQueries({queryKey:['service-principals']});setCredential(value);}}/><CredentialDialog credential={credential} onOpenChange={(open)=>{if(!open)setCredential('')}}/></div>
}
function PrincipalRow({principal,onCredential}:{principal:Awaited<ReturnType<typeof listServicePrincipals>>[number];onCredential:(value:string)=>void}){const client=useQueryClient();const status=useMutation({mutationFn:()=>updateServicePrincipalStatus(principal.id,principal.status==='active'?'disabled':'active'),onSuccess:()=>client.invalidateQueries({queryKey:['service-principals']})});const rotate=useMutation({mutationFn:()=>rotateServicePrincipalCredential(principal.id),onSuccess:(value)=>{client.invalidateQueries({queryKey:['service-principals']});onCredential(value.credential)}});return <div className="grid grid-cols-[minmax(0,1fr)_8rem_10rem_2rem] items-center gap-3 border-b px-4 py-3 last:border-b-0"><span className="flex min-w-0 items-center gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-md border"><Bot className="size-4"/></span><span className="min-w-0"><span className="block truncate text-xs font-medium">{principal.name}</span><span className="block truncate text-[11px] text-muted-foreground">{principal.description||principal.id}</span></span></span><span className="text-xs capitalize text-muted-foreground">{principal.status}</span><span className="text-xs text-muted-foreground">{principal.lastUsedAt?new Date(principal.lastUsedAt).toLocaleString():'Never'}</span><DropdownMenu><DropdownMenuTrigger asChild><Button aria-label={`Manage ${principal.name}`} size="icon-sm" variant="ghost"><MoreHorizontal/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem disabled={rotate.isPending} onSelect={()=>rotate.mutate()}><RefreshCw/>Rotate credential</DropdownMenuItem><DropdownMenuItem disabled={status.isPending} onSelect={()=>status.mutate()}>{principal.status==='active'?'Disable':'Enable'} principal</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>}
function CreateDialog({open,onOpenChange,onCreated}:{open:boolean;onOpenChange:(open:boolean)=>void;onCreated:(credential:string)=>void}){const[name,setName]=useState('');const[description,setDescription]=useState('');const create=useMutation({mutationFn:()=>createServicePrincipal({name,description}),onSuccess:(value)=>{setName('');setDescription('');onOpenChange(false);onCreated(value.credential)}});return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>New service principal</DialogTitle><DialogDescription>A credential is generated once and stored only as a hash.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={(e)=>{e.preventDefault();create.mutate()}}><Field label="Name"><Input autoFocus value={name} onChange={(e)=>setName(e.target.value)}/></Field><Field label="Description"><Input value={description} onChange={(e)=>setDescription(e.target.value)}/></Field>{create.isError&&<p className="text-xs text-destructive">{create.error instanceof Error?create.error.message:'Unable to create principal.'}</p>}<Button className="w-full" disabled={!name.trim()||create.isPending}>{create.isPending?'Creating…':'Create principal'}</Button></form></DialogContent></Dialog>}
function CredentialDialog({credential,onOpenChange}:{credential:string;onOpenChange:(open:boolean)=>void}){return <Dialog open={Boolean(credential)} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Save this credential</DialogTitle><DialogDescription>It will not be shown again. Store it in the calling system’s secret manager.</DialogDescription></DialogHeader><div className="flex items-center gap-2 rounded-md border bg-muted/40 p-3"><KeyRound className="size-4 shrink-0"/><code className="min-w-0 flex-1 break-all text-xs">{credential}</code><Button aria-label="Copy credential" onClick={()=>navigator.clipboard.writeText(credential)} size="icon-sm" variant="ghost"><Copy/></Button></div><Button onClick={()=>onOpenChange(false)}>I’ve saved it</Button></DialogContent></Dialog>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block space-y-2"><span className="text-xs font-medium">{label}</span>{children}</label>}
function State({text}:{text:string}){return <p className="px-4 py-12 text-center text-xs text-muted-foreground">{text}</p>}
